let alumni = {
    "alumn_2021" : 
    [
        { name: "Puja Acharjee",                    dept: "CHEMISTRY"           },
        { name : "Nikita Agarwal",                  dept: "CSE"                 },
        { name : "Bikoshita Gogoi",                 dept: "CSE"                 },
        { name: "Meenakshi Das",                    dept: "MBBT"                },                            
        { name : "Rupa Deka ",                      dept: "CSE"                 },                          
        { name : "Anju Chetry",                     dept: "CSE"                 },
        { name : "Maitreyee Phukan",                dept: "ECE"                 },
        { name : "Pritirekha Dutta",                dept: "ECE"                 },
        { name : "Elura Sonowal",                   dept: "ECE"                 },
        { name : "Meghna Roy",                      dept: "CSE"                 },
        { name : "Darshana Baruah",                 dept: "CSE"                 },
        { name : "Harshita Yadav",                  dept: "CSE"                 },
        { name : "Sonia Raj Gurung",                dept: "CE"                  },
        { name : "Musuka Basumatary",               dept: "ECE"                 },
        { name : "Bandita Deka",                    dept: "Physics"             },
        { name : "Rebika Salam",                    dept: "FET"                 },
        { name : "Dimpal Pathak",                   dept: "MCJ"                 },
        { name : "Ananya Das",                      dept: "Mathmatics"          },
        { name : "Didriksha Saikia",                dept: "MCJ"                 },
        { name : "Sebanki Biswas ",                 dept: "ECE"                 },
        { name : "Sweta Chatterjee",                dept: "MCJ"                 },
        { name : "Arpita Deb",                      dept: "MCJ"                 },
        { name : "Dimpi saikia",                    dept: "EVS"                 },
        { name : "Alboni bora",                     dept: "EVS"                 },
        { name : "Sushmita Das",                    dept: "EVS"                 },
        { name : "Rashmi Roy ",                     dept: "EVS"                 },
        { name : "Ojosmita B. Goswami",             dept: "CSE"                 },
        { name : "Nitumoni Neog",                   dept: "CSE"                 },
        { name : "Alankrita Priyadarshini",         dept: "CSE"                 },
        { name : "Bijita Singha",                   dept: "CSE"                 },
        { name : "Christeena Borah",                dept: "FET"                 },
        { name : "Ambika Swargiary",                dept:"MECHANICAL"           },
        { name : "Shraddha Kundu",                  dept: "MATHEMATICS"         },
        { name : "Rajnandanee Biswas",              dept: "CSE"                 },
        { name : "Riddhi Saikia",                   dept: "CHEMICAL SIENCES"    },
        { name : "Ridom Risha Gogoi",               dept: "CHEMICAL SIENCES"    },
        { name : "Jemima Yasmin",                   dept: "CE"                  },
        { name : "Diksha Dutta",                    dept: "CE"                  },
        { name : "Ekha",                            dept: "CSE"                 },
        { name : "Jenifa",                          dept: "MBBT"                },
        { name : "Prodipti Dutta",                  dept:"MECHANICAL"           },
        { name : "Dibyani Lahon",                   dept:"MECHANICAL"           },
        { name : "Riya Ahmed",                      dept: "MBBT"                },
        { name : "Priyadarshini",                   dept: "FET "                },
        { name : "Anjali Singh Basfor",             dept: "MBBT"                },
        { name : "Banamaya Goyari",                 dept: "MATHEMATICS"         },
        { name : "Sikhashree Barman",               dept: "MATHEMATICS"         },
        { name : "Koyel Ray",                       dept: "MBBT"                },
        { name : "Piyali Dey",                      dept:"MECHANICAL"           },
        { name : "Saphy",                           dept : "CSE"                },
        { name : "Kashmiri Borah",                  dept : "CSE"                },
        { name : "Upasana Parasar ",                dept : "CHEMICAL SCIENCES"  },
        { name : "Pritymala Basumatary",            dept : "ECE"                },
        { name : "Barsa Rani Dey",                  dept : "MBBT"               },
        { name : "Aditi Gogoi ",                    dept : "CSE"                },
        { name : "Singamayum Firdosh Nesha ",       dept : "FET"                },
        { name : "Trishna Mani Deka ",              dept : "MCJ"                },
        { name : "Khusboo Das",                     dept : "CSE"                },
        { name : "Smitakshi Goswami",               dept : "Physics"            },
        { name : "Prakriti Dutta",                  dept : "FET"                },
        { name : "Dorothi Hazarika",                dept : "ECE"                },
        { name : "Risha Kalita",                    dept : "CHEMICAL SCIENCES"  },
        { name : "Baishali Gogoi",                  dept : "ECE"                },
        { name : "Raaya Zaman",                     dept : "EFL"                },
        { name : "Chayanika Pegu",                  dept : "CHEMICAL SCIENCES"  },
        { name : "Juli Rani Basumatary",            dept : "CIVIL"              },
        { name : "Rezoom Chakma",                   dept : "CSE"                },
        { name : "Shreoshri Kashyap",               dept : "CIVIL"              },
        { name : "Mayur Trishna Saikia",            dept : "CIVIL"              },
        { name : "Prantika Ojah ",                  dept : "EVS"                },
        { name : "Bhavna Dutta",                    dept : "EVS"                },
        { name : "Zeenat Mazid",                    dept : "MCJ"                },
        { name : "Dimple Baro",                     dept : "MCJ"                },
        { name : "Pujashree Gogoi",                 dept : "FET"                },
        { name : "Rosy Saikia ",                    dept : "CHEMICAL SCIENCES"  },
        { name : "Sorokhaibom Romita Devi ",        dept : "FET"                },
        { name : "Smriti Roy",                      dept : "PHYSICS"            },
        { name : "Kaumudi Saikia",                  dept : "CHEMICAL SCIENCES"  },
        { name : "Jonmoni Dutta",                   dept : "PHYSICS"            },
        { name : "Nikita Buragohain",               dept : "MCJ"                },
        { name : "Shubhangi Saini",                 dept : "MBBT"               },
        { name : "Yasmin Ara Begum",                dept : "EVS"                },
        { name : "Anisha Hazarika",                 dept : "EVS"                },
        { name : "Trinita Singha Roy",              dept : "CHEMICAL SCIENCES"  },
        { name : "Afreen Hussain",                  dept : "CHEMICAL SCIENCES"  },
        { name : "Nurin Afzia",                     dept : "FET"                },
        { name : "Monica Deb",                      dept : "UNKNOWN"            },
        { name : "Sweta Das",                       dept : "CIVIL"              },
        { name : "Liza Hazarika",                   dept : "MATHEMATICS"        },
        { name : "Pinky Chetry",                    dept : "CSE"                },
        { name : "Sanahanbi Khangembam",            dept : "EVS"                },
        { name : "Tridisha Sharma ",                dept : "EVS"                },
        { name : "Bharoti Payeng",                  dept : "EVS"                },
        { name : "Pompi Talukdar ",                 dept : "MECHANICAL"         },
        { name : "Nitisha Kaushik ",                dept : "CSE"                },
        { name : "Ruchika Bhoot",                   dept : "CSE"                },
        { name : "Pragya Das",                      dept : "CIVIL"              },
        { name : "Debajani Deori",                  dept : "MECHANICAL"         },
        { name : "Sukanya Chetia",                  dept : "CHEMICAL SCIENCES"  },
        { name : "Snigdha Das  ",                   dept : "ECE"                },
        { name : "Dorothy Das",                     dept : "ECE"                },
        { name : "Swapna Mondal",                   dept : "MATHEMATICS"        },
        { name : "Sreeja Saha",                     dept : "MATHEMATICS"        },
        { name : "Nipona Shill",                    dept : "FET"                },
        { name : "Meghali Das",                     dept : "PHYSICS"            },
        { name : "Saumyashree",                     dept : "MBBT"               },
        { name : "Priyanka",                        dept : "MBBT"               },
        { name : "Sika Teronpi",                    dept : "CHEMICAL SCIENCES"  },
        { name : "Sibani Dhar",                     dept : "CHEMICAL SCIENCES"  },
        { name : "Sanghamitra Sarkar",              dept : "CSE"                },
        { name : "Atifa Sarkar",                    dept : "CHEMICAL SCIENCES"  },
        { name : "Reshma Begum",                    dept : "CHEMICAL SCIENCES"  },
        { name : "Flora Emilia Basumatary",         dept : "CHEMICAL SCIENCES"  },
        { name : "Chayanika Chetia",                dept : "MBBT"               },
        { name : "Himakshi Brahma",                 dept : "ECE"                },
        { name : "Deepika Mandal",                  dept : "EVS"                },
        { name : "Mridula Dhar",                    dept : "EVS"                },
        { name : "Shikhamoni Nath",                 dept : "MATHEMATICS"        },
        { name : "Latashree Gogoi",                 dept : "CSE"                },
        { name : "Liza Dutta",                      dept : "PHYSICS"            },
        { name : "Priyanka Dey",                    dept : "PHYSICS"            },
        { name : "Piyali Das",                      dept : "MCJ"                },
        { name : "Himakshi Deka",                   dept : "MATHEMATICS"        },
        { name : "Rimjyoti Baishya ",               dept : "MATHEMATICS"        },
        { name : "Himangshi Deka",                  dept : "MATHEMATICS"        },
        { name : "Trisha Khound",                   dept : "ECE"                },
        { name : "Elora Nath",                      dept : "CHEMICAL SCIENCES"  },
        { name : "Himashri Das",                    dept : "CHEMICAL SCIENCES"  },
        { name : "Reema Basumatary",                dept : "MATHEMATICS"        },
        { name : "Shraddha Sinha",                  dept : "CIVIL"              },
        { name : "Sneha Talukdar",                  dept : "CIVIL"              },
        { name : "Kasturi Bora",                    dept : "CSE"                },
        { name : "Ishika Sharma",                   dept : "CSE"                },
        { name : "Parishmita Borah",                dept : "MATHEMATICS"        },
        { name : "Lovita Das",                      dept : "MATHEMATICS"        },
        { name : "Kumkum Bhuyan",                   dept : "CIVIL"              },
        { name : "Ananya Thakur",                   dept : "FET"                },
        { name : "Smita Roy",                       dept : "CIVIL"              },
        { name : "Trishti Panging",                 dept : "CIVIL"              },
        { name : "Lubana Ishrat",                   dept : "EVS"                },
        { name : "Jumana Ishrat",                   dept : "CHEMICAL SCIENCES"  },
        { name : "Unnayana Gogoi",                  dept : "CHEMICAL SCIENCES"  },
        { name : "Bhavna Choudhary",                dept : "CHEMICAL SCIENCES"  },
        { name : "Richa Brahma",                    dept : "CHEMICAL SCIENCES"  },
        { name : "Karishma RayChoudhury",           dept : "ECE"                },
        { name : "Aditi Das ",                      dept : "MATHEMATICS"        },
        { name : "Pallavi Prajapati",               dept : "CSE"                },
        { name : "Simashree Saikia",                dept : "CHEMICAL SCIENCES"  },
        { name : "Pranamika Chetia",                dept : "CSE"                },
        { name : "Rituparna Borah ",                dept : "ECE"                },
        { name : "Isha Sasdeva",                    dept : "MBBT"               },
        { name : "Shilpa Chauhan",                  dept : "MBBT"               },
        { name : "Meghna Baruah",                   dept : "CIVIL"              },
        { name : "Trishna Das",                     dept : "ENERGY"             },
        { name : "Krishnamoni Gogoi",               dept : "ENERGY"             },
        { name : "Bandita Rajkhowa",                dept : "MBBT"               },
        { name : "Sufee Sahin",                     dept : "ECE"                },
        { name : "Rinki Gogoi",                     dept : "EE"                 },
        { name : "Mehjebin Wahid",                  dept : "MATHEMATICS"        },
        { name : "Bijay Laxmi Viswas",              dept : "CSE"                },
        { name : "Nitumoni Sonowal",                dept : "EVS"                },
        { name : "Khila Devi Khatiwoda",            dept : "EVS"                },    
        { name : "Aadrita Das",                     dept : "EVS"                },
        { name : "Barbie Duarah",                   dept : "CSE"                },
        { name : "Upasana Kalita",                  dept : "CHEMICAL SCIENCES"  },
        { name : "Kashyapi Dowerah",                dept : "CHEMICAL SCIENCES"  },
        { name : "Sampriti Bora ",                  dept : "PHYSICS"            },
        { name : "Sabiba Ahmed",                    dept : "PHYSICS"            },
        { name : "Kankita Nath",                    dept : "CSE"                },
        { name : "Sukla Das",                       dept : "FET"                },
        { name : "Prena Mehta",                     dept : "FET"                },
        { name : "Ruplekha Bordoloi",               dept : "CHEMICAL SCIENCES"  },
        { name : "Meethi Buragohain ",              dept : "PHYSICS"            }
    ]
}

// table 2011
let listOne ='';
let counterOne = 1;
for (let item of alumni ['alumn_2011'].values()) {
    listOne += `<tr>
                <th scope="row">${counterOne}</th>
                <td>${item['name']}</td>
                <td>${item['dept']}</td>
            </tr>`;
    counterOne = counterOne + 1;
}
document.getElementById("alumni-data-1").innerHTML = listOne;