let alumni11 = {
    "alumni_2011" : 
    [
        { name : "Aishwraya Banerjee",      dept : "MBA"                            },
        { name : "Priyanka Amonge",         dept : "MBA"                            },
        { name : "Disha Bhuyan",            dept : "MBA"                            },
        { name : "Sagarika Bhuyan",         dept : "EFL"                            },
        { name : "Munmi Borkokoty",         dept : "Mathematical Sciences"          },
        { name : "Chandrali Das",           dept : "Mathematical Sciences"          },
        { name : "Swikrita Dowerah",        dept : "MCJ"                            },
        { name : "Deepsikha Bhattacharya",  dept : "MBA"                            },
        { name : "Yogita Goswami",          dept : "Cultural Studies"               },
        { name : "Mohsina Rahman",          dept : "MCJ"                            },
        { name : "Rituparna Deka",          dept : "MBBT"                           },
        { name : "Mrinmoyee Dutta",         dept : "MBBT"                           },
        { name : "Neelam Nayan Borah",      dept : "MBBT"                           },
        { name : "Vanlalrinchhani",         dept : "MBBT"                           },
        { name : "Meenu Joshi",             dept : "MBA"                            },
        { name : "Namrata Sharma",          dept : "MBA"                            },
        { name : "Hiran Chetri",            dept : "Chemical Sciences"              },
        { name : "Dipsikha Bharali",        dept : "Chemical Sciences"              },
        { name : "Bidisha Konwar",          dept : "Chemical Sciences"              },
        { name : "Purabi Bhagawati",        dept : "Sociology"                      },
        { name : "Panchali Borua",          dept : "Sociology"                      },
        { name : "Reema Goswami",           dept : "EVS"                            },
        { name : "Rupjyoti Gogoi",          dept : "EVS"                            },
        { name : "Banashree Sharmah",       dept : "EVS"                            },
        { name : "Rubi Pegu",               dept : "ECE (Mtech)"                    },
        { name : "Barnali Sharmah",         dept : "ECE (Mtech)"                    },
        { name : "Kanta Roy",               dept : "MBA"                            },
        { name : "Kakoli Devi",             dept : "Chemical Science"               },
        { name : "Subhasmita Boro",         dept : "ECE (Mtech)"                    },
        { name : "Tribeni Lakshmi Saikia",  dept : "Cultural Studies"               },
        { name : "Upasana Sharma",          dept : "MCJ"                            },
        { name : "Palakshi Goswami",        dept : "MCJ"                            },
        { name : "Phibabondor S. Warjri",   dept : "ECE (Mtech)"                    },
        { name : "Surashmi Bhattacharya",   dept : "Mathematical Sciences"          },
        { name : "Sangita Boruah",          dept : "Mathematical Sciences"          },
        { name : "Smita Saikia",            dept : "Chemical Sciences"              },
        { name : "Popi Goswami",            dept : "Cultural Studies"               },
        { name : "Ankita Borah",            dept : "MBBT"                           },
        { name : "Chenole Keppen",          dept : "MBBT"                           },
        { name : "Arpana Das",              dept : "MCJ"                            },
        { name : "Hiramoni Das",            dept : "MCJ"                            },
        { name : "Moonmoon Konwar",         dept : "MBA"                            },
        { name : "Anuradha Dutta",          dept : "MBA"                            },
        { name : "Mayuri Rajbonshi",        dept : "Cultural Studies"               },
        { name : "Akangsha Saikia",         dept : "Cultural Studies"               },
        { name : "Ipshita Sinha",           dept : "EVS"                            },
        { name : "Kuntala Dowarah",         dept : "Sociology"                      },
        { name : "Nivedita Saikia",         dept : "EFL"                            },
        { name : "Juti Deka",               dept : "EFL"                            },
        { name : "Sukanya Borgohain",       dept : "MBA"                            },
        { name : "Sujata Saha",             dept : "MBA"                            },
        { name : "Aijoni Doley",            dept : "MBA"                            },
        { name : "Deiji Hazarika",          dept : "Cultural Studies"               },
        { name : "Prathana Archarya",       dept : "EFL"                            },
        { name : "Ishani Nath",             dept : "EFL"                            },
        { name : "Deepika Paul",            dept : "Sociology"                      },
        { name : "Sangeeta Saikia",         dept : "Sociology"                      },
        { name : "Banashree Saharia",       dept : "EVS"                            },
        { name : "Jutika Chetia",           dept : "MCJ"                            },
        { name : "Rituparna Borah",         dept : "Chemical sciences"              },
        { name : "Ashmita Bharali",         dept : "EVS"                            },
        { name : "Kanki Hazarika",          dept : "MCJ"                            },
        { name : "Ricky Kumari Shah",       dept : "MCJ"                            },
        { name : "Anindita Gogoi",          dept : "EVS"                            },
        { name : "Manjushree Shail",        dept : "MBBT"                           },
        { name : "Swapna ojah",             dept : "MTech (Energy)"                 },
        { name : "Bijumoni rajbongshi",     dept : "MTech (Energy)"                 },
        { name : "Somadrita Deb",           dept : "Chemical sciences"              },
        { name : "Shilpi Baglari",          dept : "Chemical sciences"              },
        { name : "Pakiza Begum",            dept : "Chemical sciences"              },
        { name : "Shalini Khan",            dept : "ECE (Btech)"                    },
        { name : "Ananya Gogoi",            dept : "ECE (Btech)"                    },
        { name : "Priyanki Banerjee",       dept : "MCJ"                            },
        { name : "Shibani Gogoi",           dept : "Mathematical Sciences"          },
        { name : "Kalyani Devi",            dept : "Cultural Studies"               },
        { name : "Chitralekha Narzary",     dept : "Cultural Studies"               },
        { name : "Munmi Gohain",            dept : "Physics"                        },
        { name : "Kabyashree Borah",        dept : "Physics"                        },
        { name : "Tarun Kumari",            dept : "Mathematical Sciences"          },
        { name : "Pearl Sancheyata Gogoi",  dept : "Mathematical Sciences"          },
        { name : "Tilottama Balari",        dept : "MBA"                            },
        { name : "Vaishali Phukan",         dept : "Mathematical Sciences"          },
        { name : "Shatabdi Bhattacharjee",  dept : "MBBT"                           },
        { name : "Krishna Sharma",          dept : "EFL"                            },
        { name : "Naaz Afreen",             dept : "EFL"                            },
        { name : "Akashi Borah",            dept : "Mathematical Sciences"          },
        { name : "Konkana Boruah",          dept : "Mathematical Sciences"          },
        { name : "Samarpita Choudhary",     dept : "MCJ"                            },
        { name : "Debi Das",                dept : "MCJ"                            },
        { name : "Jinty Rajkhowa",          dept : "Sociology"                      },
        { name : "Antara Bhattacharjee",    dept : "Mathematical Sciences"          },
        { name : "Archana Mena",            dept : "Mathematical Sciences"          },
        { name : "Bandana Devi",            dept : "MCJ"                            },
        { name : "Anwesha Dey",             dept : "MCJ"                            },
        { name : "Antara Choudhary",        dept : "EFL"                            },
        { name : "Ranjita Das",             dept : "Mtech (IT)"                     },
        { name : "Tinamoni Saikia&nbsp",    dept : "Cultural Studies"               },
        { name : "Lizamoni Bhattacharya",   dept : "Cultural Studies"               },
        { name : "Niharika Mahanta",        dept : "EFL"                            },
        { name : "Kakumoni Saikia",         dept : "EFL"                            },
        { name : "Padmaja Tamuli",          dept : "MCJ"                            },
        { name : "Surekha Bhuyan",          dept : "MCJ"                            },
        { name : "Madhusmita Dutta",        dept : "MBA"                            },
        { name : "Ekta Kumari",             dept : "MBA"                            },
        { name : "Aarti Kumari",            dept : "MBBT"                           },
        { name : "Pradakshina Sharma",      dept : "Sociology"                      },
        { name : "Manika Adhikary",         dept : "Sociology"                      },
        { name : "Gitimoni Saikia",         dept : "Mtech (IT)"                     },
        { name : "Suparna Biswas",          dept : "Mathematical Sciences (MSc)"    },
        { name : "Pinkimoni Goswami",       dept : "Mathematical Sciences (MSc)"    },
        { name : "Suni Rudrapal",           dept : "MBA"                            },
        { name : "Palashi Bora",            dept : "MBA"                            },
        { name : "Arpee Saikia",            dept : "MBA"                            },
        { name : "Himani Saikia",           dept : "MCJ"                            },
        { name : "Sandhaya Rani Gogoi",     dept : "Chemical Sciences"              },
        { name : "Nandita Debnath",         dept : "Mtech (IT)"                     },
        { name : "Rajashree Saharia",       dept : "Sociology"                      },
        { name : "Barsha Bhattacharya",     dept : "Sociology"                      },
        { name : "Sanghita Dutta",          dept : "EVS"                            },
        { name : "Arunima Goswami",         dept : "Cultural Studies"               },
        { name : "Giturani Kalita",         dept : "Cultural Studies"               },
        { name : "Girbani Deka",            dept : "Mathematical Sciences"          },
        { name : "Pallabi Saikia",          dept : "Mathematical Sciences"          },
        { name : "Samanwita Goswami",       dept : "MBBT"                           },
        { name : "Priyanka Roy",            dept : "MBBT"                           },
        { name : "Himadri Medhi",           dept : "Nanoscience"                    },
        { name : "Pangkita Deka",           dept : "Chemical Science"               },
        { name : "Anupama Handique",        dept : "MBA"                            },
        { name : "Priyanka Konwar",         dept : "MBA"                            },
        { name : "Jumi Neog",               dept : "Mathematical Sciences (MSc)"    },
        { name : "Santana Hazarika",        dept : "Mathematical Sciences (MSc)"    },
        { name : "Sukanya Kalita",          dept : "EFL"                            },
        { name : "Jonali Rabha",            dept : "EFL"                            },
        { name : "Mauchumi Das",            dept : "MBA"                            },
        { name : "Sikha Baishya",           dept : "MBA"                            },
        { name : "Jonali Sarma",            dept : "Sociology"                      },
        { name : "Meghali das",             dept : "Sociology"                      }    
    ]
}

// table 2011
let alumniList11 ='';
let alumniCounter11 = 1;
for (let item of alumni11 ['alumni_2011'].values()) {
    alumniList11 += `<tr>
                <th scope="row">${alumniCounter11}</th>
                <td>${item['name']}</td>
                <td>${item['dept']}</td>
            </tr>`;
            alumniCounter11 = alumniCounter11 + 1;
}
document.getElementById("alumni-data-2").innerHTML = alumniList11;